mapper = {
    "Notebook Pro 15": "Notebook Pro 15",
    "Smartphone X": "Smartphone X",
    "Fone Bluetooth": "Bluetooth Headphones",
    "Smart TV 50\"": "50\" Smart TV",
    "Mouse Gamer": "Gaming Mouse",
    "Teclado Mecânico": "Mechanical Keyboard",
    "Monitor 27\"": "27\" Monitor",
    "Câmera Digital": "Digital Camera",
    "Tablet Plus": "Tablet Plus",
    "Carregador USB": "USB Charger",
    "Cadeira Gamer": "Gaming Chair",
    "Mesa Escritório": "Office Desk",
    "Sofá 3 Lugares": "3-Seater Sofa",
    "Estante de Livros": "Bookshelf",
    "Guarda-Roupa": "Wardrobe",
    "Cama Box": "Box Bed",
    "Poltrona": "Armchair",
    "Rack TV": "TV Stand",
    "Mesa Jantar": "Dining Table",
    "Banco Alto": "Bar Stool",
    "Camiseta Básica": "Basic T-Shirt",
    "Calça Jeans": "Jeans",
    "Jaqueta": "Jacket",
    "Vestido Casual": "Casual Dress",
    "Tênis Esportivo": "Sports Sneakers",
    "Moletom": "Sweatshirt",
    "Shorts": "Shorts",
    "Saia": "Skirt",
    "Camisa Social": "Dress Shirt",
    "Meias": "Socks",
    "Liquidificador": "Blender",
    "Air Fryer": "Air Fryer",
    "Cafeteira": "Coffee Maker",
    "Micro-ondas": "Microwave",
    "Geladeira": "Refrigerator",
    "Fogão": "Stove",
    "Aspirador Pó": "Vacuum Cleaner",
    "Ventilador": "Fan",
    "Batedeira": "Stand Mixer",
    "Sanduicheira": "Sandwich Maker"
}
